### PR TITLE
Eliminate dependencies

### PR DESCRIPTION
**Pull request by isiahmeadows**
I pulled and merged the regexps from is-glob and is-extglob into this, making it have 0 dependencies. Incidentally, it's about as simple otherwise.

### CODE REVIEW

**Comment by isiahmeadows** [comment]
@es128 Welcome :smile: 

I realized this while debugging a project inside Node Inspector, and I found it was loading three different files just to go through this.

**Comment by isiahmeadows** [comment]
The last update fixed where I incorrectly merged the regexps.

**Comment by es128** [comment]
Thanks for the PR. 

Care to explain more about why you think I should merge this? To reduce `require` slowness? Or as a reaction to the left-pad fallout?

In a general sense, I'm perfectly happy to leave @jonschlinkert in charge of maintaining that regex. It's not as if I never realized I had the option of copying it. If you're on a mission to reduce/consolidate dependencies, you are of course free to use your fork or just use the snippet and copy it wherever you intend to use it. 

I'm interested to hear some others' perspectives on this before deciding what to do with the PR.

**Comment by jonschlinkert** [comment]
I wasn't going to respond, but IMO merging this PR would support a terrible anti-pattern. this kind of thinking demonstrates the exact problem that node.js solves. 

Who cares about how many modules it is? Distribution methods and storage will continue to optimize over time. The point is that any chunk of code that can be used in more than one lib and can be made to be self-encapsulated will be more stable, unit-testable, and more likely to be exposed to domain expertise from more developers who can benefit and optimize that chunk of code. This advocates the opposite. 

Not to mention, um, wow... @isiahmeadows you know that's not actually your code to copy, right?

sorry for the flamage. this is just lame, I hate when people steal code and think it's okay

**Comment by isiahmeadows** [comment]
Okay. I'll close.

**Pull request closed without merging**
