### PR TITLE
Update is-glob dependency

### PR DESCRIPTION
**Pull request by phated**
Due to https://github.com/jonschlinkert/is-glob/issues/4 and https://github.com/jonschlinkert/is-glob/issues/5 - `is-glob` has been bumped to 3.0

I'm not sure if you want to bump major or something less.  The implementation has gotten more complex but matching has gotten more precise.

### CODE REVIEW

**Comment by es128** [comment]
What do you suggest regarding the version? I don't get the impression that the changes would lead to something someone would consider "breaking", but I suppose the chance is there. 

I guess I'm leaning toward major bump, but interested in other opinions before I go ahead.

**Comment by jonschlinkert** [comment]
I personally would do a major, but I think @phated's opinion on this is more important.

**Comment by phated** [comment]
The question that you/we need to ask is "was anyone depending on broken matches/false positives?".  If someone was relying on `test (123)` or `(test|123}` to be a glob.  If the answer could be yes, then release it as a major (also leaning towards).

It doesn't really matter to me because I noticed a bug in glob-stream that this change fixes so I'll be bumping as a patch.

**Comment by es128** [comment]
Meh, I could make the argument both ways, neither side is definitively winning in my head. 

Just gonna go major and be done with it.

**Pull request merged**
